version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: >
     bash -c 'rm -f /parking_lot/tmp/pids/* &&
              bundle check ||
              bundle install &&
              bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/parking_lot
    ports:
      - "3000:3000"
    depends_on:
      - db
