default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: <%= ENV['PGHOST'] %>
  pool: 5

development:
  <<: *default
  database: parking_lot_development


test:
  <<: *default
  database: parking_lot_test
